BioSR:
  epochs: 100
  batch_size: 12
  learning_rate: 0.0001
  weight_decay: 0.00001
  lambda_LL: 0.01
  lambda_SSIM: 0.1
  lambda_sp: 0.1

BPAEC:
  epochs: 10
  batch_size: 8
  learning_rate: 0.00001
  weight_decay: 0.00001
  lambda_LL: 0.01
  lambda_SSIM: 0.1
  lambda_sp: 0.1